[package]
name = "evm-bot"
version = "0.1.4"
authors = ["Deezzir <deezzir@gmail.com>"]
description = "EVM Bot CLI"
edition = "2024"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Deezzir/evm-bot"

[package.metadata.deb]
maintainer = "Deezzir <deezzir@gmail.com>"
section = "utility"
priority = "optional"
assets = [
    ["target/release/evm-bot", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/evm-bot/README.md", "644"],
    ["CONTRIBUTING.md", "usr/share/doc/evm-bot/CONTRIBUTING.md", "644"],
    ["LICENSE", "usr/share/doc/evm-bot/LICENSE", "644"],
]

[dependencies]
alloy = { version = "2.0", features = [
    "network",
    "provider-http",
    "provider-ws",
    "rpc-types-eth",
    "signer-local",
    "contract",
    "reqwest",
] }

tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive", "cargo"] }
serde = { version = "1.0", features = ["derive"] }
csv = "1.4"
figlet-rs = "1.0"
colored = "2"
dotenv = "0.15"
chrono = "0.4.45"
anyhow = "1.0.104"
serde_json = "1.0.151"
reqwest = { version = "0.13.4", features = ["json", "query"] }
num-format = "0.4.4"
futures = "0.3.34"

[dev-dependencies]
tempfile = "3"
